'use client'

import { useProModal } from "@/hooks/use-pro-modal"
import { Dialog, DialogContent } from "../ui/dialog"
import Image from "next/image"
import { LoaderButton } from "../ui/loader-button"
import { useState } from "react"
import axios from "axios"
import { useToast } from "../ui/use-toast"
import { cn } from "@/lib/utils"

const ProModal = () => {

    const proModal = useProModal()

    const [isLoading, setIsLoading] = useState(false)

    const { toast }= useToast()

    const onClick = async () => {
      try {
        setIsLoading(true);
        const response = await axios.get("/api/stripe");
  
        window.location.href = response.data.url;
      } catch (error: any) {
        if (error.response) {
            const errorMessage = error.response.data || 'An error occurred';
            toast({
                variant: 'destructive',
                title: errorMessage
            })
        } else {
            console.error('Error:', error.message);
        }
      } finally {
        setIsLoading(false)
      }
    }

  return (
    <Dialog open={proModal.isOpen} onOpenChange={proModal.onClose}>
      <DialogContent className="max-w-md p-0 overflow-hidden">
        <div className="aspect-video relative flex items-center justify-center">
          <Image src="/cosmic.png" alt="Hero" className="object-cover" fill/>
          <div className="absolute inset-0 bg-black opacity-20"></div> 
          <div className="absolute right-2 bottom-0 text-xs text-white font-medium">
             Generated by <a href="https://hotpot.ai/art-generator" target="_blank" className="hover:underline">hotpot.ai</a>
          </div>
        </div>
        <div className="text-neutral-700 mx-auto space-y-4 p-6">
          <h2 className="font-semibold text-xl">
            Upgrade to LinkedForgeAI Pro today!
          </h2>
          <p className="text-sm font-semibold text-neutral-600">
            For only <span className="text-lg font-bold">29.99$</span> per month
          </p>
          <div className="pl-3">
            <ul className="text-sm list-disc">
              <li>Unlimited conversations</li>
              <li>10k messages per month</li>
              <li>7 active assistants</li>
              <li>Priority email support</li>
            </ul>
          </div>
          <LoaderButton disabled={isLoading} isLoading={isLoading} onClick={onClick} className={cn("w-full", isLoading && "cursor-default")} variant="purple">
            Upgrade
          </LoaderButton>
        </div>
      </DialogContent>
    </Dialog>
  )
}

export default ProModal